---
title: "Class 8"
output: 
  html_document:
    keep_md: true
    theme: paper
---

``` {r}
# install.packages("here")
# install.packages("readxl")
# install.packages("haven")
# install.packages("ggthemes")
# install.packages("svglite")
# install.packages("rio")
```

``` {r}
library(tidyverse)
library(gapminder)
library(here)
library(readxl) 
library(haven)
library(dplyr)
library(ggthemes)
library(svglite)
library(rio)
```

```{r allow errors, echo = FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r, echo = FALSE}
gap_asia_2007 <- gapminder %>% 
  filter(year == 2007, continent == "Asia") %>%
print()
```

```{r, echo=FALSE}
write_csv(gap_asia_2007, "exported_file.csv")
```

```{r, echo=FALSE}
write_csv(gap_asia_2007, here::here("data", "s008_data", "exported_file.csv"))
```

```{r, echo=FALSE}
read_csv(here::here("data", "s008_data", "exported_file.csv"))
```
```{r}
url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv"
```

```{r}
read_csv(url)
```

```{r}
read_csv("http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv")
```

```{r}
dir.create(here::here("data", "s008_data"), recursive = TRUE)
```

```{r}
xls_url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls"
download.file(xls_url, here::here("data", "s008_data", "some_file.xls"), mode = "wb")
```

```{r}
file_name <- basename(xls_url)
download.file(xls_url, here::here("data", "s008_data", file_name), mode = "wb")
```

```{r}
read_excel(here::here("data", "s008_data", file_name))
```

```{r}
(clevel <- haven::read_spss(here::here("data", "s008_data", "clevel.sav")))
```

```{r}
clevel_cleaned <-
  clevel %>% 
  mutate(language = as_factor(language),
         gender = as_factor(gender),
         isClevel = factor(isClevel, 
                           levels = c(0, 1), 
                           labels = c("No", "Yes"))
  ) %>% 
  print()
```

```{r}
write_csv(clevel_cleaned, here::here("data", "s008_data", "clevel_cleaned.csv"))
```

```{r}
clevel_plot <-
  clevel_cleaned %>% 
  mutate(isClevel = recode(isClevel, 
                           No = "Below C-level", 
                           Yes = "C-level"),
         gender = recode(gender,
                         Female = "Women",
                         Male = "Men")) %>% 
  ggplot(aes(paste(isClevel, gender, sep = "\n"), Extraversion, color = gender)) +
  geom_boxplot() +
  geom_jitter(height = .2) +
  scale_color_manual(values = c("#1b9e77", "#7570b3")) +
  ggtitle("Extraversion Stan Scores") +
  scale_y_continuous(breaks = 1:9) +
  ggthemes::theme_fivethirtyeight() %>% 
  print()
```

```{r}
dir.create(here::here("output", "figures"))
ggsave(here::here("output", "figures", "clevel_extraversion.svg"), clevel_plot)
```

```{r}
ggsave(here::here("output", "figures", "clevel_extraversion.eps"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.pdf"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.tiff"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.png"), clevel_plot)
```

```{r}
rio::import("clevel.sav", setclass = "tibble", format("sav"))
```

